//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinMadOpskrift
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bruger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bruger()
        {
            this.Opskrift = new HashSet<Opskrift>();
        }
    
        public int ID { get; set; }
        public string Brugernavn { get; set; }
        public string Password { get; set; }
        public int Alder { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opskrift> Opskrift { get; set; }
    }
}
